[project]
name = "andes365"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.4.0",
    "ipykernel>=6.30.1",
    "kaggle>=1.7.4.5",
    "kagglehub>=0.3.13",
    "pandas>=2.3.2",
    "pyspark>=4.0.1",
]
